version: '3.4'

# general python base for future services like celery
x-base-python: &x-base-python
  build:
    context: .
    dockerfile: ./Dockerfile
  image: crypto_proxy_img
  environment:
    - PYTHONUNBUFFERED=1
  restart: always



services:
  app:
    <<: *x-base-python
    command: poetry run python3  -m crypto_proxy
    container_name: crypto-proxy
    depends_on:
      - memcached
    ports:
      - "8000:8000"
    hostname: app
    volumes:
      - .:/app/crypto_proxy


  memcached:
    image: memcached
    command: memcached -m 1024M -I 32M
    container_name: memcached
    ports:
      - "11211:11211"
    hostname: app
    volumes:
      - .:/app/crypto_proxy


networks:
  default:
    external:
      name: localdev